# Header
menu:
  - name: 'Time Attack Records'
    url: '/time-attack-records'
  - name: 'Teamz'
    url: '/teamz'
    children:
      - name: 'Generator'
        url: '/teamz/generator'
      - name: 'Results'
        url: '/teamz/results'
      - name: 'Leaderboards'
        url: '/teamz/leaderboards'   
  - name: 'Concepts'
    url: '/concepts'
    children:
      - name: 'Sandbox TA'
        url: '/concepts/sandbox-ta'
  - name: 'Servers'
    url: '/servers'
    children:
      - name: 'Clementine'
        url: '/servers/gamecube'
  - name: 'Players'
    url: '/players'
  - name: 'Miscellaneous'
    url: '/miscellaneous'
  - name: 'PSU: TA Discord'
    url: 'https://discord.gg/W4M79kA'

# Content
excerpt_link: Read More

# Miscellaneous
google_analytics: UA-159966586-1
twitter:
fb_admins:
fb_app_id:
